### ISSUE TITLE
Termux | Android

### ISSUE THREAD

**Issue by BCanary** [pentestxr/Fludilka#3]
Все скопировать не смог. Термукс даже переустановил и сделал все по инструкции в readme 1 в 1. Root права нужны?

/termux/pytransform/__init__.py", line 259, in _load_library
    m = cdll.LoadLibrary(filename)
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 447, in LoadLibrary
    return self._dlltype(name)
  File "/data/data/com.termux/files/usr/lib/python3.8/ctypes/__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen failed: "/data/data/com.termux/files/home/Fludilka/termux/pytransform/_pytransform.so" is 64-bit instead of 32-bit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Fludilka/termux/pytransform/__init__.py", line 295, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix)
  File "/data/data/com.termux/files/home/Fludilka/termux/pytransform/__init__.py", line 289, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix)
  File "/data/data/com.termux/files/home/Fludilka/termux/pytransform/__init__.py", line 261, in _load_library
    raise PytransformError('Load %s failed:\n%s' % (filename, e))
pytransform.PytransformError: Load /data/data/com.termux/files/home/Fludilka/termux/pytransform/_pytransform.so failed:
dlopen failed: "/data/data/com.termux/files/home/Fludilka/termux/pytransform/_pytransform.so" is 64-bit instead of 32-bit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fludilka.py", line 2, in <module>
    pyarmor_runtime()
  File "/data/data/com.termux/files/home/Fludilka/termux/pytransform/__init__.py", line 298, in pyarmor_runtime
    raise PytransformError(e)
pytransform.PytransformError: Load /data/data/com.termux/files/home/Fludilka/termux/pytransform/_pytransform.so failed:
dlopen failed: "/data/data/com.termux/files/home/Fludilka/termux/pytransform/_pytransform.so" is 64-bit instead of 32-bit

**Comment by BCanary** [comment]
Не до конца развернул readme, походу рут права все таки нужны :/
